// import './js/about-me';
// import './js/benefits.js';
// import './js/covers.js';
// import './js/faq.js';
// import './js/header.js';
import '../src/js/project';
// import './js/reviews.js';
// import './js/swagger-api.js';
// import './js/work-together.js';
// import './js/scroll-to-top.js';
// import './js/animations.js';
